ragflow:
  host: ${RAGFLOW_HOST:-0.0.0.0}
  http_port: 9380
admin:
  host: ${RAGFLOW_HOST:-0.0.0.0}
  http_port: 9381
mysql:
  name: '${MYSQL_DBNAME:-rag_flow}'
  user: '${MYSQL_USER:-root}'
  password: '${MYSQL_PASSWORD:-infini_rag_flow}'
  host: '${MYSQL_HOST:-mysql}'
  port: 3306
  max_connections: 900
  stale_timeout: 300
  max_allowed_packet: ${MYSQL_MAX_PACKET:-1073741824}
minio:
  user: '${MINIO_USER:-rag_flow}'
  password: '${MINIO_PASSWORD:-infini_rag_flow}'
  host: '${MINIO_HOST:-minio}:9000'
es:
  hosts: 'http://${ES_HOST:-es01}:9200'
  username: '${ES_USER:-elastic}'
  password: '${ELASTIC_PASSWORD:-infini_rag_flow}'
os:
  hosts: 'http://${OS_HOST:-opensearch01}:9201'
  username: '${OS_USER:-admin}'
  password: '${OPENSEARCH_PASSWORD:-infini_rag_flow_OS_01}'
infinity:
  uri: '${INFINITY_HOST:-infinity}:23817'
  db_name: 'default_db'
redis:
  db: 1
  password: '${REDIS_PASSWORD:-infini_rag_flow}'
  host: '${REDIS_HOST:-redis}:6379'
# postgres:
#   name: '${POSTGRES_DBNAME:-rag_flow}'
#   user: '${POSTGRES_USER:-rag_flow}'
#   password: '${POSTGRES_PASSWORD:-infini_rag_flow}'
#   host: '${POSTGRES_HOST:-postgres}'
#   port: 5432
#   max_connections: 100
#   stale_timeout: 30
# s3:
#   access_key: 'access_key'
#   secret_key: 'secret_key'
#   region: 'region'
#   endpoint_url: 'endpoint_url'
#   bucket: 'bucket'
#   prefix_path: 'prefix_path'
#   signature_version: 'v4'
#   addressing_style: 'path'
# oss:
#   access_key: '${ACCESS_KEY}'
#   secret_key: '${SECRET_KEY}'
#   endpoint_url: '${ENDPOINT}'
#   region: '${REGION}'
#   bucket: '${BUCKET}'
#   prefix_path: '${OSS_PREFIX_PATH}'
# azure:
#   auth_type: 'sas'
#   container_url: 'container_url'
#   sas_token: 'sas_token'
# azure:
#   auth_type: 'spn'
#   account_url: 'account_url'
#   client_id: 'client_id'
#   secret: 'secret'
#   tenant_id: 'tenant_id'
#   container_name: 'container_name'
# The OSS object storage uses the MySQL configuration above by default. If you need to switch to another object storage service, please uncomment and configure the following parameters.
# opendal:
#   scheme: 'mysql'  # Storage type, such as s3, oss, azure, etc.
#   config:
#     oss_table: 'opendal_storage'
user_default_llm:
  factory: 'VLLM'
  base_url: 'http://172.21.0.7:8000/v1'
  api_key: 'token-abc123'
  default_models:
    chat_model:
      name: 'Qwen/Qwen2.5-7B-Instruct'
    embedding_model:
      name: 'bge-m3'
      factory: 'BAAI'
    rerank_model: 'BAAI/bge-reranker-v2-m3'
    asr_model:
      model: 'whisper-large-v3' # alias of name
    image2text_model: ''

# Optimized retrieval and chat settings for better accuracy
retrieval:
  similarity_threshold: 0.6        # Increased from 0.2 for better quality
  vector_similarity_weight: 0.7    # Increased from 0.3 for semantic priority
  top_n: 5                         # Keep optimal value

rerank:
  model: "BAAI/bge-reranker-v2-m3"  # Best reranker model
  enabled: true                     # Enable reranking

optimization:
  multi_turn: true                  # Enable multi-turn optimization
  knowledge_graph: false            # Can try true later

llm:
  temperature: 0.1                  # Reduced from 0.7 for less hallucination
  top_p: 0.9                        # Keep optimal value
  presence_penalty: 0.6             # Increased from 0.0 for better responses
  frequency_penalty: 0.0            # Keep optimal value
  max_tokens: 512                   # Keep optimal value
  max_context_tokens: 25000         # Limit context to prevent overflow

system_prompt: "You are a professional AI assistant. When responding to questions about any document type:

1. ALWAYS ask clarifying questions when:
   - Multiple sections/pages exist: 'Which specific section/page do you want me to focus on?'
   - Information is ambiguous: 'Could you clarify what specific information you're looking for?'
   - Multiple interpretations possible: 'Are you asking about [option A] or [option B]?'
   - Context is unclear: 'What time period/scope are you interested in?'

2. ALWAYS provide source citations:
   - Document name: 'Source: [Document Name]'
   - Page/section references: 'Found on page X, section Y'
   - Specific locations: 'Located in [specific part of document]'
   - For Excel: 'Sheet: [Sheet Name], Cell: A1'

3. ALWAYS include confidence scores:
   - High confidence (90-100%): 'I'm 95% confident this information is accurate'
   - Medium confidence (70-89%): 'I'm 80% confident, but please verify'
   - Low confidence (<70%): 'I'm 60% confident, this may need verification'

4. For any document type:
   - Ask for clarification when information is incomplete
   - Specify which part of the document contains the answer
   - Indicate if the information might be outdated or incomplete
   - Suggest additional sources if available

Here is the knowledge base:
{knowledge}
The above is the knowledge base.

If no relevant information is found, say 'Not found in knowledge base.'"
# oauth:
#   oauth2:
#     display_name: "OAuth2"
#     client_id: "your_client_id"
#     client_secret: "your_client_secret"
#     authorization_url: "https://your-oauth-provider.com/oauth/authorize"
#     token_url: "https://your-oauth-provider.com/oauth/token"
#     userinfo_url: "https://your-oauth-provider.com/oauth/userinfo"
#     redirect_uri: "https://your-app.com/v1/user/oauth/callback/oauth2"
#   oidc:
#     display_name: "OIDC"
#     client_id: "your_client_id"
#     client_secret: "your_client_secret"
#     issuer: "https://your-oauth-provider.com/oidc"
#     scope: "openid email profile"
#     redirect_uri: "https://your-app.com/v1/user/oauth/callback/oidc"
#   github:
#     type: "github"
#     icon: "github"
#     display_name: "Github"
#     client_id: "your_client_id"
#     client_secret: "your_client_secret"
#     redirect_uri: "https://your-app.com/v1/user/oauth/callback/github"
# authentication:
#   client:
#     switch: false
#     http_app_key:
#     http_secret_key:
#   site:
#     switch: false
# permission:
#   switch: false
#   component: false
#   dataset: false
# smtp:
#   mail_server: ""
#   mail_port: 465
#   mail_use_ssl: true
#   mail_use_tls: false
#   mail_username: ""
#   mail_password: ""
#   mail_default_sender:
#     - "RAGFlow" # display name
#     - "" # sender email address
#   mail_frontend_url: "https://your-frontend.example.com"
