services:
  vllm:
    image: vllm/vllm-openai:latest
    command: --model Qwen/Qwen2.5-7B-Instruct --dtype auto --api-key token-abc123 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - HF_ENDPOINT=https://hf-mirror.com
    volumes:
      - /tmp/additional-storage/huggingface-cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
